### PR TITLE
Prepare for release v1.6.2 0.4.4

### PR DESCRIPTION
**Pull request by zouzias**
Hi there,

This is a proposal for release with Spark 1.6.2.

Can you create a branch named `release-v1.6.2_0.4.4` so that I can PR there? I currently do this PR on master.

### CODE REVIEW

**Comment by holdenk** [comment]
Thanks for making this PR! :) So we probably want to instead update `mini-cross-build.pl` to add 1.6.2 to the list of spark_versions we make releases for (although having CI validate that it builds ok against 1.6.2 as this PR does is a good first step).

**Comment by zouzias** [comment]
I see. You do the releases with `mini-cross-build.pl`. 

I guess then on this branch we can test Spark 1.6.2 and never merge it. If test succeeds, we can add 1.6.2 `in mini-cross-build.pl` in a different PR.

**Comment by holdenk** [comment]
Yup! Sadly cross building for different versions of Spark isn't well supported by any of the spark-package tooling I can find (if you happen to know of anything better I'd really love to get rid of the perl script I use to create releases).

**Comment by zouzias** [comment]
For building and testing, we can use a similar approach with https://github.com/databricks/spark-csv/blob/master/.travis.yml

For releases of multiple spark versions, unfortunately I am not aware of any relevant tooling.

**Comment by holdenk** [comment]
Oooh I do like that travis approach :)

**Comment by huitseeker** [comment]
I'm kinda unsure about of the set of commits that this includes, given the target merge branch. You may want to double-check /  rebase, @zouzias

**Comment by zouzias** [comment]
I did a bit of rebasing / commit squashing. Now, it is a single commit.

**Comment by zouzias** [comment]
@holdenk, I did a conservative version update on the projects dependencies using the `sbt-updates` plugin  following @huitseeker suggestion.

**Comment by holdenk** [comment]
This looks good, I'm going to change the default build back to 2.0 after merge but thanks for checking for 1.6.2 support and updating some of the deps :)

**Comment by zouzias** [comment]
Cool, thanks @holdenk! Yes, it makes sense to have 2.0 as default.

**Pull request merged**
