### PR TITLE
Version bump, closes #217

### LINKED ISSUE #217: StructuredStreamingBase missing inside 2.2.0_0.8.0
Hi,

I could see StructuredStreamingBase was added here https://github.com/holdenk/spark-testing-base/pull/210

But it's not packaged inside 2.2.0_0.8.0
* https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spark-testing-base_2.11%22

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by andrusha**
Library needs to be re-published.

### CODE REVIEW

**Comment by holdenk** [comment]
Cool, can you update the Python version as well?

**Comment by andrusha** [comment]
I guess https://github.com/holdenk/spark-testing-base/commit/ccebb559e4ab6c18492f5a4b09d18954d5909645 when published to Maven will solve this

**Comment by nightscape** [comment]
@andrusha @holdenk a new release containing the nullable stuff would be nice, but I think this PR can be closed, at least with the outdated version number it currently uses.

**Comment by holdenk** [comment]
Was in a motorcycle crash. I’ll see when I have the time but focused on health for the next while.

**Comment by nightscape** [comment]
@holdenk 😨
I hope no unrecoverable injuries?!? 😱 😱 😱 
We wish you all the best!

**Comment by andrusha** [comment]
@holdenk get well! I'm closing this PR since it's unrelated now

**Pull request closed without merging**
