### PR TITLE
ADD RDDComparison Java support and unify all assert methods' names to use assert...Equals

### PR DESCRIPTION
**Pull request by mahmoudhanafy**
#87

### CODE REVIEW

**Comment by holdenk** [comment]
This looks good :) Yay for making it easier for Java. We might want to (as a follow up) add grouping for the generated docs so the asserts are grouped together.

**Comment by holdenk** [comment]
It seems like some of these changes maybe meant to go to another branch?

**Comment by holdenk** [comment]
Oh or maybe just change the title to mention both.

**Comment by holdenk** [comment]
This looks good if we can update the title, maybe we can merge this and the PR with out the partitioner requirement for withOrder and then make a release yah?

**Comment by mahmoudhanafy** [comment]
Yes, I think you can merge #79 first then I will rebase on your changes.

**Pull request merged**
