### PR TITLE
Support Spark 2.4.7 and 3.0.2

### PR DESCRIPTION
**Pull request by limansky**

### CODE REVIEW

**Comment by limansky** [comment]
Hi @holdenk 

Any chance to have it merged?

**Comment by limansky** [comment]
Hi @holdenk ,

 I've updated the patch to add Spark 2.4.7 as well.

**Comment by limansky** [comment]
Hi @holdenk,

  I've resolved conflicts in this PR.

**Comment by limansky** [comment]
Hi @holdenk,

 I've added Spark 3.0.2 to this PR. Could you please check?

**Review by holdenk — APPROVED** [review]
LGTM

**Comment by holdenk** [comment]
Can you resolve the conflicts though? Rebase on master.

**Comment by limansky** [comment]
@holdenk Done. I've squashed all previous patches into one commit on top of master.

**Pull request merged**
