### PR TITLE
Update Spark version to 2.1.1

### PR DESCRIPTION
**Pull request by zouzias**
Update for Spark 2.1.1 release.

Moreover,
* Update sbt to 0.13.15
* Update scala 2.11 to 2.11.11

### CODE REVIEW

**Comment by holdenk** [comment]
I've merged this but temporarily put us down to the same Scala version as the current Spark - are there some issues/features in 2.1.11 that would help?

**Comment by zouzias** [comment]
Cool, thanks!

No worries about keeping old scala version. Just tried to keep us
up-to-date with scala 2.11.



Am 06.05.2017 09:41 schrieb "Holden Karau" <notifications@github.com>:

I've merged this but temporarily put us down to the same Scala version as
the current Spark - are there some issues/features in 2.1.11 that would
help?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/holdenk/spark-testing-base/pull/184#issuecomment-299622644>,
or mute the thread

**Comment by zouzias** [comment]
I see now what you meant ( https://github.com/apache/spark/blob/v2.1.1/pom.xml#L2716 ), yes makes sense to keep the same scala version with Spark.

**Comment by holdenk** [comment]
Awesome, thanks for the PR I'll try and make a release with it soon :) always happy to have more people working on the library :)

**Pull request merged**
