### PR TITLE
Add JavaPairRDD support at JavaRDDComparisons

### PR DESCRIPTION
**Pull request by mahmoudhanafy**

### CODE REVIEW

**Comment by holdenk** [comment]
What about if we just took "JavaRDDLike" since its a common trait to both?

**Comment by mahmoudhanafy** [comment]
How to support one type parameter for `JavaRDD[T]` and two type parameters for `JavaPairRDD[K, V]` with `JavaRDDLike` interface ?

**Comment by holdenk** [comment]
So for the ones where we need the K/V pair keep JavaPairRDD but for `assertPairRDDEqualsWithOrder` we could just change `assertRDDEqualsWithOrder` to take `JavaRDDLike`.

**Comment by holdenk** [comment]
Going to close for now since were fairly far out of sync

**Pull request closed without merging**
