### PR TITLE
Support Spark 3.0.0

### LINKED ISSUE #323: Upgrade to Spark 3.0.0
After the release of Spark 3.0.0, this library should be compatible with the new spark version.

### PR DESCRIPTION
**Pull request by lunaticare**
Fixes #323

Changes:
* remove defunct Spray artifact repository
* ignore Bloop and Metals work files

### CODE REVIEW

**Comment by ashikaumanga** [comment]
I built this branch using `sbt  -DsparkVersion=3.0.0 -DscalaVersion=2.12.11  version clean +publishLocal`
And used in my Spark 3.0 Scala project (scala 2.12.11) using :
`"com.holdenkarau" %% "spark-testing-base" % "3.0.0_0.14.0" % "test",`

But when I run my unit tests,its throws this error : 

> [info] com.rakuten.dps.dataplatform.redbasket.driver.logic.DemoModule1LogicSpec *** ABORTED ***
> [info]   java.lang.IncompatibleClassChangeError: Expected instance not static method org.scalatest.Assertions.assertionsHelper()Lorg/scalatest/Assertions$AssertionsHelper;
> [info]   at com.holdenkarau.spark.testing.TestSuite.assert(TestSuite.scala:19)
> [info]   at com.holdenkarau.spark.testing.TestSuite.assert$(TestSuite.scala:18)

Anyway to fix this ?

**Comment by lunaticare** [comment]
> I built this branch using sbt -DsparkVersion=3.0.0 -DscalaVersion=2.12.11 version clean +publishLocal
And used the library in my Spark 3.0 Scala project (scala 2.12.11) using :
"com.holdenkarau" %% "spark-testing-base" % "3.0.0_0.14.0" % "test",

> But when I run my unit tests,its throws this error :

@ashikaumanga according to [this](https://stackoverflow.com/questions/1980452/what-causes-java-lang-incompatibleclasschangeerror), the error might mean your project need to be recompiled.

Could you also specify which version of Scalatest your projects uses?

**Comment by JohnEngelhart** [comment]
When can we expect this PR to be merged?

**Comment by holdenk** [comment]
I think we'll need some more changes beyond this, but good start.

**Pull request merged**
