### PR TITLE
Support Scala 2.12

### LINKED ISSUE #273: Add scala 2.12 support
We used to also support 2.10 so similar logic can be used.

### PR DESCRIPTION
**Pull request by limansky**
This is my attempt to fix #273.

### CODE REVIEW

**Comment by MDIB** [comment]
We will have to bump `spark-streaming-kafka` component to `0-10` I tried locally and it break a lot of stuff :cry:

**Comment by limansky** [comment]
@MDIB Thanks. It seems like the problem is bit deeper that just package version, because the API in different spark-steraming-kafka modues is different. So, the different sources should be used with different spark versions. Should both 0.8 and 0.10 be supported for Spark 2.4.0 (at least for Scala 2.11)?

If so, then there should be separate packages `spark-testing-kafka-0.8` and `spark-testing-kafka-0.10`.  In this case it is possible to support kafka 0.10 for other Spark versions (as i remember spark streaming-kafka-0.10 is available since Spark 2.0.0).

@holdenk It would be nice to know your opinion on this problem.

**Comment by limansky** [comment]
JFYI, I've started to implement it as I describe in previous comment here https://github.com/limansky/spark-testing-base/tree/multiproject. I'll update this pull request as soon as I will have something working :)

**Comment by holdenk** [comment]
This is AWESOME so excited!

**Comment by holdenk** [comment]
I think it's ok for us to just say if your in Spark 2.4+ we only do Kafka 0.10 but multi project is also an option if you want to go that way :)

**Comment by holdenk** [comment]
Just following up @limansky if this is a thing your still working on I'd be happy to help in any way I can. If it's become more frustrating than fun though no stress and I'll pick it up in the new year :)

**Comment by limansky** [comment]
Hi @holdenk. I'd like to continue working on this issue during new year holidays. There several issues:

- [ ] cross-building of multi-module project (different crossScalaVersions per subproject). There are several options to solve it:
  - Use `sbt-doge` (which is deprecated, because this feature is already included in sbt-1.x)
  - Upgrade to sbt 1.x and use `sbt-spark-packages` from this pull request https://github.com/databricks/sbt-spark-package/pull/41 (because there is no stable version for sbt-1.x yet)
  - Upgrade to sbt 1.x and get rid of `sbt-spark-packages` (do all this stuff manually).
  - Move all kafka related stuff to separate repositories. 
- [ ]  The kafka related code is not compatible with kafka 0.10, so changing dependency is not the only problem. My plan is to split `spark-testing-base` into two packages first, and then focus on porting to new kafka (possible in separate pull request).

@holdenk what do you think about the first one?

**Comment by MrPowers** [comment]
@limansky - Here's how we [added Scala 2.12 support to spark-daria](https://github.com/MrPowers/spark-daria/commit/dcbdd09d3899025339792b23632a35b474471717).

We upgraded to SBT 1.2.6 and got spark-packages with this:

```scala
resolvers += Resolver.bintrayIvyRepo("s22s", "sbt-plugins")
addSbtPlugin("org.spark-packages" % "sbt-spark-package" % "0.2.7-astraea.1")
```

@oscarvarto did all the heavy lifting.

Let me know if this helps!

**Comment by limansky** [comment]
@MrPowers thanks, I've seen this. Do you is there any plans to have official release of sbt-spark-package?

**Comment by MrPowers** [comment]
@limansky - I've [opened some issues in the past](https://github.com/databricks/sbt-spark-package/issues/31) in the sbt-spark-package repo and they didn't get much love.  Don't think the project is really maintained anymore so I wouldn't count on a release anytime soon.

**Comment by limansky** [comment]
@holdenk ok. I'll do.

**Comment by limansky** [comment]
@holdenk Could you please review this pull requiest? I removed sbt-spark-package. Here is no Kafka 0.10 support yet, but it unlock compile core part with Scala 2.12 for those who don't need Kafka related features.
BTW, I'm not sure if there should be some additional actions in the build script for Python support.

**Comment by limansky** [comment]
Meanwhile I created a separate branch https://github.com/limansky/spark-testing-base/tree/kafka_0_10 for Kafka 0.10 support. It looks like Kafka API is changed dramatically btw.

**Comment by holdenk** [comment]
Awesome, thanks for working on this! I'm behind on some work for a conference so I'm having to put my other stuff on hold until that gets done but I'm hoping to have some time next week.

**Comment by holdenk** [comment]
Update: my optimism was misplaced but should have cycles next week.

**Comment by limansky** [comment]
Hi @holdenk! 
I've found that there are no Spark 2.2.2 artifacts published anymore. So travis builds fail. I've fixed it in the last commit. BTW, any news about this pull request?

**Comment by limansky** [comment]
Hi @holdenk!
I've updated pull request to support Spark 2.3.3 and 2.4.1, and changed travis build to use Spark 2.3.3, because it's a lowest version available now. Could you please take a look on this?

**Comment by nonsleepr** [comment]
Any updates on it?

**Comment by holdenk** [comment]
Thanks for the awesome work! This looks good to me with a first pass now that CI is green, I'll do a more thorough review on Monday but hopefully merge it next week :)

**Comment by holdenk** [comment]
Actually this looks good, I'll do some small fixes around how the perl scripts works but those don't need to hold this up :)

**Pull request merged**
