### PR TITLE
Adding support for JDK 17

### LINKED ISSUE #358: Support JDK17

### PR DESCRIPTION
**Pull request by edmondop**
This PR adds support for JDK 17 by adding exceptions to new visibility rules introduced by Java 17. The exceptions are taken from the Spark official repository https://github.com/apache/spark/pull/34153

Fixes #358

### CODE REVIEW

**Comment by holdenk** [comment]
This is awesome! Thanks @edmondop  :D

**Comment by holdenk** [comment]
Ah slight problem with the tests. Let me get the tests running on PRs later this week and we can redo.

**Comment by edmondop** [comment]
Tests were running for me locally but I couldn't trigger the build on the CI. Let me look into those...

> Ah slight problem with the tests. Let me get the tests running on PRs later this week and we can redo.

**Comment by edmondop** [comment]
I see, the problem is only with the distribution not being set in the github workflows. What JDK do you want to use?open jdk?

**Pull request merged**
