### PR TITLE
Setting Shuffle Partitions in order to limit the number of Tasks

### PR DESCRIPTION
**Pull request by qnob**
Significant reduce of memory usage and execution time.

### CODE REVIEW

**Comment by MrPowers** [comment]
@qnob - this is pretty huge.  Just added it to some of my projects and it sped up the test suites 30%, 66% and 70%.  Massive difference.  I think you should reopen this PR.

**Comment by qnob** [comment]
Hello Matthew,

yes, I know. We have a bunch of tests that were running slow and run into out of memory in your in pipeline. It looks like this configuration puts spark into a single thread mode, that performs much better for small data. However, I cannot the estimate eventual site effects.

After having some troubles with the build, I've had opened another PR, see
https://github.com/holdenk/spark-testing-base/pull/293 

The long answer is, if you're interested, I still haven't got the whole picture, but it looks like Spark, in local mode, uses about 5 worker threads  for processing its tasks. The default configuration would create 200 tasks, if shuffling is involved. In our case, the 200 tasks were a huge overhead, since we write tests with datasets of a couple of rows only. In order words, I think the needed configuration might depend on the amount of data you're using in your test.

Greets
K

**Comment by MrPowers** [comment]
@qnob - Thanks for the description.  The new PR looks similar to this one, just with a typo fixed.

Like you alluded to, different users will have a different number of optimal shuffle partitions.  Most users probably use tiny DataFrames when testing and can just use a single shuffle partition, but some users will probably need more.

It might be good for you to pull out the number of partitions to a separate method so users could override it... not sure if that's possible.  Maybe we can set the default to "1" and let the other users increase that if they're testing big DataFrames.

In any case, thanks again for pointing this out and sharing it with the community.  Some of my private repos have test suites than run 70% faster now - that's huge!

**Comment by qnob** [comment]
Hi again, 
actually, I already did overwrite the property somehow, without modifying the original distribution. 
It's a sort of hack, but it might inspire you for an even greater hack :).
I'll send you a code snipped on Monday, when I'll be back in my office.

Kuno

**Comment by MrPowers** [comment]
Awesome, let's hack away!  I will eagerly await your code on Monday.  Thanks!

**Comment by qnob** [comment]
Hello Matthew,
as promised, here is my current workaround:

I've extended  all my test classes following trait : 

```
trait MinimalHardwareResources extends SparkContextProvider {
  override def conf: SparkConf = {
    super.conf.set("spark.sql.shuffle.partitions", "1")
  }
}
```

Actually, it's already possible to overwrite spark configuration. 

In my opinion, following things should be decided:

1. What would be the best default value?
-> Value of 1 is quite restrictive. Value of 5 is more pragmatic, but creates "unnecessary" threads,..

2. Should we improve documentation?
-> Performance issues and fixes should be mentioned somewhere.

Greets

**Comment by rbramley** [comment]
This config change made a major difference (90% reduction) to the test suite execution time for a project that uses the GraphFrames implementation of connected components. 

Note that the GraphFrames test suites use 4 partitions: 
https://github.com/graphframes/graphframes/blob/a30adaf53dece8c548d96c895ac330ecb3931451/src/test/scala/org/graphframes/GraphFrameTestSparkContext.scala#L62

**Pull request closed without merging**
