### PR TITLE
Add Spark 2.4.4 support.

### PR DESCRIPTION
**Pull request by limansky**

### CODE REVIEW

**Comment by holdenk** [comment]
LGTM, thanks.

**Comment by limansky** [comment]
@holdenk could you please publish the artefacts as well?

**Comment by limansky** [comment]
@holdenk ping ;-)

**Comment by etspaceman** [comment]
Could we please get a release on this?

**Comment by ritvikgautam** [comment]
@holdenk

**Comment by ritvikgautam** [comment]
@mahmoudhanafy

**Comment by holdenk** [comment]
Hey sorry I was in a motorcycle accident and I can’t really do anything for probably the next two weeks

**Comment by ritvikgautam** [comment]
No worries, hope you feel better soon! (:

**Comment by kainosdataacademyjan2019g** [comment]
Hi @holdenk, do you plan to release this change? Or am I looking at wrong place: https://mvnrepository.com/artifact/com.holdenkarau/spark-testing-base ?

**Comment by holdenk** [comment]
I plan to do a release early February, road to recovery has been slow so I’ve had other more pressing items to deal with.

**Comment by kainosdataacademyjan2019g** [comment]
Thank you for the update and a date I can look forward to, all the best :).

**Comment by claudiaii** [comment]
Thanks for the update! Hope you feel better soon!

**Comment by limansky** [comment]
Hi @holdenk !

  Spark 2.4.5 have been released. I've created pull request for it: https://github.com/holdenk/spark-testing-base/pull/311 

  Could you please take a look, when you feel better? I hope it happen soon.

**Pull request merged**
