### PR TITLE
Update spark version to 2.0.1

### PR DESCRIPTION
**Pull request by zouzias**
Title says it all.

### CODE REVIEW

**Comment by holdenk** [comment]
Cool, can you also update the perl script that is used so we can cross-build?

**Comment by zouzias** [comment]
Sure, I will do asap. Cheers

Am 05.10.2016 9:02 PM schrieb "Holden Karau" <notifications@github.com>:

**Comment by zouzias** [comment]
@holdenk added Spark version 2.0.1 in 75ca9eb

**Comment by holdenk** [comment]
I'm assuming travis failure is unrelated, merging and I'll try and get an updated version out tonight :)

**Comment by zouzias** [comment]
Yes, I think so as well for travis (previous commit was successful). I also run the tests locally and everything was green.

**Pull request merged**
