### PR TITLE
Base class for testing Actions

### PR DESCRIPTION
**Pull request by jnadler**
As I said this is a little amateurish.   I took the existing base class and cut it down to create a version that does not expect/require any output.   It works though and we have a couple of tests that depend on it.

### CODE REVIEW

**Comment by holdenk** [comment]
How would you feel about adding a test using this (both to test the code & for an example for people that want to use it)?

**Comment by jnadler** [comment]
Sure, I'll take care of that this week.

**Comment by holdenk** [comment]
Awesome, thanks for taking the time to add this :)

**Comment by holdenk** [comment]
I've merged this in for now, and we can add some examples for it in another PR :)

**Pull request closed without merging**
