### PR TITLE
Timestamp Tolerance

### PR DESCRIPTION
**Pull request by chiefmanc**
Addition for tolerance of timestamps. The timestamp tolerance is in milliseconds.

### CODE REVIEW

**Comment by holdenk** [comment]
Thanks for making this PR! Would you be OK with adding a test which exercises this code path? I really like the functionality.

**Comment by holdenk** [comment]
Gentle ping @chiefmanc :) If you're around Spark Summit we can also chat IRL this week.

**Comment by holdenk** [comment]
Gentle re-ping? If you're busy I can follow up and add a test my self :)

**Comment by chiefmanc** [comment]
Apologies for going radio silent - I've been quite busy at work. I'm looking to change this slightly so that a 2D array can be passed in whereby it will take the field name and the tolerance for that specific field as this would be more beneficial, particularly since timestamps would require tolerance of something greater than 0 and decimals would require less than 0; as a result, when performing tolerance on a dataset that contains both timestamps and decimals, it gets really messy. As soon as I get to do this, I will push the change.

**Comment by holdenk** [comment]
Great! No rush :)

**Comment by holdenk** [comment]
Quick follow up :) We're getting close to the next release would be cool to have this in if you have the time, if not no worries.

**Comment by chiefmanc** [comment]
Hi @holdenk - I've committed the changes to include tests for the code as is. I am working with someone at the moment to introduce the 2D feature, but that will require a bit of time and I thought it would be useful to at least include this feature in the next release.

**Comment by holdenk** [comment]
This is great! thanks! :) +1

**Comment by holdenk** [comment]
So I think this is in the latest release, although I should update the readme to mention the new release.

**Pull request merged**
